{
 "title": "IOT - OpenThread",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mac_addr",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(bucket: \"measurements\", tag: \"mac_addr\")"
   }
  ]
 },
 "panels": [
  {
   "title": "${mac_addr} - RSSI AVG.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi_avg\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"sensor/${mac_addr}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "${mac_addr} - Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "repeat": "mac_addr",
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.mac_addr == \"${mac_addr}\" and r._field == \"temperature\")\r\n"
    }
   ]
  },
  {
   "title": "${mac_addr} - Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "repeat": "mac_addr",
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.mac_addr == \"${mac_addr}\" and r._field == \"air_quality\")\r\n"
    }
   ]
  },
  {
   "title": "${mac_addr} - Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "repeat": "mac_addr",
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.mac_addr == \"${mac_addr}\" and r._field == \"humidity\")\r\n"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"air_quality\"\r\n  )"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"temperature\"\n  )"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"humidity\"\n  )"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "nodeGraph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nedges = from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi_avg\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false) // Aggregate data to 1-hour intervals\r\n  |> map(fn: (r) => ({\r\n      id: r.mac_addr + \"-\" + r.neighbor_mac,\r\n      source: r.mac_addr,\r\n      target: r.neighbor_mac,\r\n      mainstat: string(v: math.round(x: r._value * 100.0) / 100.0), // Round to 2 decimal places\r\n      secondarystat: \"RSSI\",\r\n      thickness: math.round(x: (if r._value < 0.0 then float(v: -r._value) / 10.0 else float(v: r._value) / 10.0) * 100.0) / 100.0, // Explicit float conversion and rounding\r\n      highlighted: r._value < -70.0, // Example condition\r\n      color: if r._value < -80.0 then \"red\" else if r._value < -60.0 then \"orange\" else \"cyan\"\r\n  }))\r\n\r\nnodes = from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi_avg\")\r\n  |> group(columns: [\"mac_addr\"])\r\n  |> last() // Get the latest value for each mac_addr\r\n  |> map(fn: (r) => ({\r\n      id: r.mac_addr,\r\n      title: r.mac_addr,\r\n      mainstat: string(v: r._value),\r\n      secondarystat: \"N/A\", // Or calculate if relevant\r\n      color: if r._value < -80 then \"red\" else if r._value < -60 then \"orange\" else \"green\",\r\n      icon: \"eye\", // Example, choose based on your preference\r\n      highlighted: r._value < -70 // Example condition\r\n  }))\r\n\r\n\r\n\r\n// Output nodes and edges for the Node Graph\r\n\r\nedges\r\n"
    }
   ]
  }
 ]
}